spring.application.name=transitops-backend
server.port=8080

# ---- MySQL ----
spring.datasource.url=jdbc:mysql://localhost:3306/transitops?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ---- JWT ----
app.jwt.secret=TransitOps_Secret_Key_2026_Change_In_Production_9f8a7b6c5d4e3f2a1b0c
app.jwt.expiration-ms=86400000

# ---- CORS ----
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000
